name: "action-semantic-pull-request"

on:
  pull_request:
    types:
      - opened
      - edited

permissions:
  pull-requests: read

jobs:
  main:
    name: action-semantic-pull-request
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}