# Warning, do not check out untrusted code with
# the pull_request_target event.
on:
  pull_request:
    types: [opened, edited]

permissions:
  pull-requests: write
  contents: read

name: conventional-release-labels
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: bcoe/conventional-release-labels@v1